---
title: "2021 Consumer Complaints"
author: "Lia DeGroot"
date: "5/6/2022"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: columns

---


```{r setup, include=FALSE}

`complaints (1)` <- readRDS("~/Desktop/github_lia/DEGROOT_GITHUBHOMEWOKR/complaints (1).rds")

library(tidyverse)
library(janitor)
library(readxl)
library(scales)
library(lubridate)
library(ggthemes)
library(esquisse)
library(dplyr)
library(ggplot2)
library(flexdashboard)
library(kableExtra)
library(stringr)
library(knitr)

```


{.tabset}
-------------------------------------
    
### Complaints by Date


```{r}

complaints_bydate <- `complaints (1)` %>% 
  count(date_received)
```

```{r}
`complaints (1)`$Month <- lubridate::month(`complaints (1)`$date_received)

monthcount <- count(`complaints (1)`, Month)

ggplot(monthcount, aes(x = Month, y = n)) + 
 geom_line(color = "#F28C28") + labs(title = "Monthly Consumer Complaints", 
                    subtitle = "Total number of consumer complaints per month in 2021"
                      , y = "Number of complaints") + theme(panel.grid = element_line(color = "#8ccde3",
                                  size = 0.75,
                                  linetype = 2))
```
 
-------------------------------------
   
### Complaints by Product

   
```{r}

complaints_byproduct <- `complaints (1)` %>% 
  count(product)
ggplot(complaints_byproduct, aes(x = product, y = n)) +
  geom_col(color = "#F28C28", fill = "#F28C28") +
  coord_flip() +
  labs(title = "Consumer Compaints by Product", 
                    subtitle = "Total number of consumer complints by product 
                    in 2021"
                      , y = "Number of complaints", x = "Type of product") + 
  theme(panel.grid = element_line(color = "#8ccde3",
                                  size = 0.75,
                                  linetype = 2)) + 
                          theme(axis.text = element_text(size = 4)) +
  scale_x_discrete(labels = wrap_format(7))
 

```   

-------------------------------------

### Complaints by State 

   
```{r}
complaints_bystate <- `complaints (1)` %>% 
  count(state) 

 
```


```{r, results='asis'}

  
complaints_bystate %>% 
  knitr::kable(caption = "Consumer Complaints by State") %>% 
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE) 
  
 
```
    

-------------------------------------

### Responses to Complaints


```{r, results='asis'}

 complaints_byresponse <- `complaints (1)` %>% 
  count(company_response_to_consumer)
 
complaints_byresponse %>% 
  knitr::kable(caption = "Company Responses to Consumer Complaints") %>% 
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE) 
``` 

-------------------------------------

### About

```

The Consumer Financial Protection Bureau fields complaints from consumers about companies. 
Each year, the bureau compiles data on each of the complaints that were filed. 
This page displays information from the Consumer Finance Protection Bureau 
summarizing some of the key findings from their consumer complaints in 2021. 
On this page you’ll find a line graph displaying the change in number of complaints 
month over month throughout the entire year and a bar graph showing the number of 
complaints received over the entire year, categorized by month. If you scroll further, 
you’ll find a table summarizing the number of complaints categorized by states 
and a table summarizing the number of complaints categorized by the company’s 
responses to the complaints. 

These graphs show that in general, the number of monthly complaints increased over
the course of the year and the category that received the highest number of 
complaints was credit reporting services. 

As you read through the data, keep in mind a few caveats 

  - The monthly consumer complaint data excluded January and February
  - The responses were categorized for the purposes of the data, so it's 
    possible some responses include some nuance that can't be reflected
    in the table
    
    
    
    
    

```

